spring.datasource.url: jdbc:mysql://localhost:3306/social_media
spring.datasource.username: root
spring.datasource.password: hWN-h2z-aPE-8dQ
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: false
spring.jpa.properties.hibernate.format_sql: false

jwt.secret.access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
jwt.secret.refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==